# Generated by Django 5.2.1 on 2025-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_post_models_post_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photo')),
                ('created', models.DateField()),
            ],
        ),
    ]
